---
title: "101c_kaggle"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
head(flight_train)
```


1. delete irrelevant ones, turn categoricals into factors
2. create relevant combination variables
3. normalize all quantitative

"
```{r}
  data$Cancelled = ifelse(data$Cancelled == ”YES”, 1,0)


data_process = function(data){
  new.frame = data
  new.frame = subset(new.frame, select = -c("Ob", "O.City", "O.State", "Origin_city", "Destination_city","Org_airport_lat", "Org_airport_long", "Dest_airport_lat", "Dest_airport_long", "DAY" ))
  
  new.frame$Destination_airport = factor(new.frame$Destination_airport)
  new.frame$Origin_airport = factor(new.frame$Origin_airport)
  new.frame$DAY_OF_WEEK = factor(new.frame$DAY_OF_WEEK)
  new.frame$MONTH = factor(new.frame$MONTH)
  new.frame$AIRLINE = factor(new.frame$AIRLINE)
  new.frame$FLIGHT_NUMBER = factor(new.frame$FLIGHT_NUMBER)
  new.frame$TAIL_NUMBER = factor(new.frame$TAIL_NUMBER)
  
  new.frame$AIR_SYSTEM_DELAY = factor(new.frame$AIR_SYSTEM_DELAY)
  new.frame$SECURITY_DELAY = factor(new.frame$SECURITY_DELAY)
  
  return(new.frame)
}

trainingdata = FlightTrainNew1
p_trainingdata = data_process(trainingdata)

trainingdata$Cancelled = ifelse(trainingdata$Cancelled == "YES", 1 ,0)
testdata = FlightTestNoYNew1


testdata2 = data_process(testdata)
testdata2 = testdata2[,2:12]

trainingdata2 = data_process(trainingdata)
trainingdata2$Cancelled = trainingdata$Cancelled


trainingdataexcludena = na.exclude(trainingdata)


library(dplyr)
library(tidyr)

myList <- setNames(lapply(vector("list", ncol(trainingdata2)), function(x) x <- 0), names(trainingdata2))

# Now use that list in tidyr::replace_na 
trainingdata2 %>% replace_na(myList)

trainingdata3 = trainingdata2[,2:12]
trainingdata3$Cancelled = trainingdata$Cancelled

library(MASS)
# Fit the full model 
library(glmnet)
full.model <- glm(Cancelled ~., data = trainingdata3, family = binomial)



# Stepwise regression model
step.model <- stepAIC(full.model, direction = "both", 
                      trace = FALSE)
summary(step.model)


predictions = predict(full.model, testdata2)

predictions = ifelse(predictions>0, "YES", "NO")

write.csv(predictions, "101cpredictions.csv")
```

